PowerShell -Command "& {Get-AppxPackage *OneNote* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *3d* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage Microsoft.GamingServices |Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *communi* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *bing* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *zune* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *people* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *phone* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *solit* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *xbox* | Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *look |Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *help |Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage Microsoft.WindowsMaps |Remove-AppxPackage}"
PowerShell -Command "& {Get-AppxPackage *soundrec* | Remove-AppxPackage}"